language: c
compiler: gcc
sudo: false
env:
  global:
    - SDL_VERSION=2.0.8
    - DEPLOY_BRANCH=newengine
git:
  depth: 50
  submodules: true
jdk:
  - oraclejdk8
  
jobs:
  allow_failures:
    - os: osx
    - os: windows
    - os: linux
  include:
    - stage: init
      name: "Initialize webdav cache"
      os: linux
      cache: false
      script:
        - sh scripts/yadisk_clear.sh
    - stage: build
      name: "Build for Linux & Android"
      cache: ccache
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - p7zip-full
            - gcc-multilib
            - g++-multilib
            - libx11-dev:i386
            - libxext-dev:i386
            - x11-utils
            - libgl1-mesa-dev
            - libasound-dev
            - zlib1g:i386
            - libstdc++6:i386
            - libfuse2:i386
      before_script:
        - sh scripts/travis_common_deps.sh
        - sh scripts/travis_${TRAVIS_OS_NAME}_deps.sh
        - export ANDROID_HOME=$PWD/android-sdk-linux
        - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PWD/android-ndk
      script:
        - sh scripts/build_${TRAVIS_OS_NAME}_engine.sh
      after_script:
        - ccache --show-stats
        - sh scripts/yadisk_upload.sh Xash3DFWGS-i386.AppImage
    - # ...
      name: "Build for Windows MinGW"
      cache: ccache
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - mingw-w64-i686-dev
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
            - p7zip-full
      before_script:
        - sh scripts/travis_common_deps.sh
        - sh scripts/travis_mingw_deps.sh
      script:
        - sh scripts/build_mingw_engine.sh
      after_script:
        - ccache --show-stats
        - sh scripts/yadisk_upload.sh xash3d-mingw.7z
    - # ...
      name: "Build for OSX"
      cache: ccache
      os: osx
      before_script:
        - sh scripts/travis_common_deps.sh
        - sh scripts/travis_${TRAVIS_OS_NAME}_deps.sh
      script:
        - sh scripts/build_${TRAVIS_OS_NAME}_engine.sh
      after_script:
        - sh scripts/yadisk_upload.sh xash3d-osx.tar.bz2
    - # ...
      name: "Build for Windows MSVC"
      cache: ccache
      os: windows
      before_script:
        - sh scripts/travis_common_deps.sh
        - sh scripts/travis_${TRAVIS_OS_NAME}_deps.sh
      script:
        - sh scripts/build_${TRAVIS_OS_NAME}_engine.sh
      after_script:
        - sh scripts/yadisk_upload.sh xash3d-vc.7z xash3d-vc2008-sln.7z
    - stage: deploy
      name: "Deploy to github"
      os: linux
      cache: false
      script:
        - sh scripts/travis-deploy.sh Xash3DFWGS-i386.AppImage xash3d-mingw.7z xash3d-osx.tar.bz2 xash3d-vc.7z xash3d-vc2008-sln.7z
        
