language: c
compiler: gcc
sudo: false
env:
  global:
    - SDL_VERSION=2.0.14
git:
  depth: 50
  submodules: true

os: linux
arch:
  - aarch64
  - ppc64le
  - s390x
addons:
  apt:
    update: true
    packages:
      - libx11-dev
      - libxext-dev
      - x11-utils
      - libgl1-mesa-dev
      - libasound-dev
      - libstdc++6
      - libfuse2
      - unzip
before_script:
  - sh scripts/travis/deps_common.sh
  - sh scripts/travis/deps_${TRAVIS_OS_NAME}.sh
script:
  - sh scripts/travis/build_${TRAVIS_OS_NAME}.sh
after_script:
  - ccache --show-stats
  - sh scripts/continious_upload.sh xash3d-fwgs-${ARCH}.tar.xz xashds-linux-${ARCH}
