#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "nightfire/enginecommonheaders.h"
#include "studio.h"
#include "crtlib.h"
#include "mdldec.h"
#include "version.h"
#include "nightfire/mdlv44.h"

static mdlv44_header_t* nfHeader = NULL;

static void WriteBodyGroupInfo(FILE* fp)
{
	// TODO
}

static void WriteTextureRenderMode(FILE* fp)
{
	// TODO
}

static void WriteSkinFamilyInfo(FILE* fp)
{
	// TODO
}

static void WriteAttachmentInfo(FILE* fp)
{
	// TODO
}

static void WriteControllerInfo(FILE* fp)
{
	// TODO
}

static void WriteHitBoxInfo(FILE* fp)
{
	// TODO
}

static void WriteSequenceInfo(FILE* fp)
{
	// TODO
}

void NF_WriteQCScript(void)
{
	FILE* fp;
	char filename[MAX_SYSPATH];
	int len = 0;

	nfHeader = (mdlv44_header_t*)model_hdr;

	if ( !nfHeader )
	{
		fprintf(stderr, "INTERNAL ERROR: Missing model header pointer\n", modelfile);
		return;
	}

	len = Q_snprintf( filename, MAX_SYSPATH, "%s%s.qc", destdir, modelfile );

	if( len == -1 )
	{
		fprintf( stderr, "ERROR: Destination path is too long. Can't write %s.qc\n", modelfile );
		return;
	}

	fp = fopen( filename, "w" );

	if( !fp )
	{
		fprintf( stderr, "ERROR: Can't write %s\n", filename );
		return;
	}

	fputs( "/*\n", fp );
	fputs( "==============================================================================\n\n", fp );
	fputs( "QC script generated by Half-Life Studio Model Decompiler " APP_VERSION "\n", fp );

	fprintf( fp, "Copyright Flying With Gauss %s (c) \n\n", Q_timestamp( TIME_YEAR_ONLY ) );
	fprintf( fp, "%s.mdl\n\n", modelfile );

	fputs( "Original internal name:\n", fp );

	fprintf( fp, "\"%s\"\n\n", nfHeader->name );

	fputs( "==============================================================================\n", fp );
	fputs( "*/\n\n", fp );

	fprintf( fp, "$modelname \"%s.mdl\"\n", modelfile );

	fputs( "$cd \".\\\"\n", fp );
	fputs( "$cdtexture \".\\\"\n", fp );
	fputs( "$scale 1.0\n", fp );
	fputs( "$cliptotextures\n", fp );
	fputs( "\n", fp );

	fprintf( fp, "$flags %u\n", nfHeader->flags | STUDIO_NO_EMBEDDED_TEXTURES );

	fputs( "\n", fp );

	fprintf( fp, "$bbox %f %f %f", nfHeader->bboxMin[0], nfHeader->bboxMin[1], nfHeader->bboxMin[2] );
	fprintf( fp, " %f %f %f\n", nfHeader->bboxMax[0], nfHeader->bboxMax[1], nfHeader->bboxMax[2] );
	fprintf( fp, "$cbox %f %f %f", nfHeader->cboxMin[0], nfHeader->cboxMin[1], nfHeader->cboxMin[2] );
	fprintf( fp, " %f %f %f\n", nfHeader->cboxMax[0], nfHeader->cboxMax[1], nfHeader->cboxMax[2] );
	fprintf( fp, "$eyeposition %f %f %f\n", nfHeader->eyePosition[0], nfHeader->eyePosition[1], nfHeader->eyePosition[2] );

	fputs( "\n", fp );

	WriteBodyGroupInfo(fp);
	WriteTextureRenderMode(fp);
	WriteSkinFamilyInfo(fp);
	WriteAttachmentInfo(fp);
	WriteControllerInfo(fp);
	WriteHitBoxInfo(fp);
	WriteSequenceInfo(fp);

	fputs( "\n// End of QC script.\n", fp );
	fclose( fp );

	printf( "QC Script: %s\n", filename );
}
