# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build on Ubuntu Latest
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      artifactName: afterburner-linux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Configure for release
      working-directory: ${{runner.temp}}
      run: python3 waf configure --disable-vgui --win-style-install --build-type=release --prefix=./release
    - name: Clean
      working-directory: ${{runner.temp}}
      run: python3 waf clean
    - name: Build
      working-directory: ${{runner.temp}}
      run: python3 waf build
    - name: Install
      working-directory: ${{runner.temp}}
      run: python3 waf install --strip-to-file
